apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "terraria.fullname" . }}
  labels:
{{ include "terraria.labels" . | indent 4 }}
data:
  server.conf: |
{{ .Values.terraria.settings | indent 4 }}
  tshock.json: |
{{ toJson .Values.terraria.tshock | indent 4 }}
  sscconfig.json: |
{{ toJson .Values.terraria.sscconfig | indent 4 }}
